require("core.packer")
require("core.remap")
require("core.help")
require("core.ricordi")
require("core.plugin")
require("core.debugger")
require("core.checkDipendenze")
require("core.plugin.virtualmachine")
